name: CI

on:
  push:
    branches:
      - main
      - master
      - github-actions # TODO
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.3.0
      - run: curl --silent --location https://raw.githubusercontent.com/esp-rs/rust-build/main/install-rust-toolchain.sh | bash
      - run: cargo build --release
